### ISSUE TITLE
Add a tile does not save

### ISSUE THREAD

**Issue by MFerrulli** [Merkie/freespeech#113]
**Describe the bug**
Can make a tile that works but cannot save it.

**To Reproduce**
1. Go to Firefox> freespeechaac.com
2. Click on 'Edit'
3. At top, click 'Add a Tile'
4. Add one, then try to save it

**Expected behavior**
I expected to see a tile show up on the page

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Device name	Mary
Processor	Intel(R) Core(TM) i7-8700T CPU @ 2.40GHz   2.40 GHz
Installed RAM	16.0 GB (15.8 GB usable)
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

Edition	Windows 10 Pro
Version	20H2
Installed on	‎7/‎30/‎2020
OS build	19042.1415
Experience	Windows Feature Experience Pack 120.2212.3920.0

 - Browser Firefox
 - Version 95.0.1 (64-bit)

**Comment by Carlos-Gaxiola** [comment]
Hello, I am trying to replicate this bug, but I don't see a button to "Add a tile". Where is this option?

**Comment by fatfingers23** [comment]
Want to note for anyone who sees this issue and want's to help with it. I have removed the Add tile button for now since it was a bug in production and caused users not able to edit their tiles. Can see what the code was [here](https://github.com/Merkie/freespeech/commit/6c6d6a46afd0dc1f902c5217a5f97649134bf6d4#diff-019e4fc594c18738d748e3c1389a30728c01b846a59ce3d552978a8ba439348fL19) to add it back and troubleshoot.

**Comment by Carlos-Gaxiola** [comment]
> troubleshoot

Nice, I will be seeing this issue and try to figure out a solution!
