### ISSUE TITLE
Default voice and lanuage

### ISSUE THREAD

**Issue by aidankinzett** [Merkie/freespeech#51]
Every time I restart the app my voice and language defaults to Arabic (Saudi Arabia) and I live in Australia. Could we detect the devices region/language to set the default voice? Or at least default to a generic American voice

**Comment by Philipdev95** [comment]
Or have some cookies/localstorage that remembers your last choice.

**Comment by fatfingers23** [comment]
I agree. I notice there is a default that gets returned from getvoices. That may help, not sure if just one is set as default though.

@Philipdev95 is it not remembering your last choice? It should be. Our vuex store syncs to local storage If not that's a bug.

**Comment by Philipdev95** [comment]
> @Philipdev95 is it not remembering your last choice? It should be. Our vuex store syncs to local storage If not that's a bug.

Well for @aidankinzett it does not seem to do that?

**Comment by fatfingers23** [comment]
I’m sorry. You’re exactly right. Went completely over my head.

Could you make a new issue @aidankinzett following the bug template for it not saving your voice on restart so we can get the full details please.

I think this issue is a great place for the setting or a default voice and the new issue for the bug fix of not saving.

**Comment by aidankinzett** [comment]
Sorry I think I was wrong, it does save in my local storage. I was mistaken from it changing language when opening new browsers or on different devices.
