### ISSUE TITLE
Draft Overview Of Features A Backend Would Provide

### ISSUE THREAD

**Issue by fatfingers23** [Merkie/freespeech#71]
**This is a draft of features that creating a backend will provide. This is a high overview and is subject to change. This is non technical and only focus on end user features. These are vague on purpose. Individual issues will be created later to fully flesh out the ideas here. Suggestions  are welcome, but please keep them constructive.**

### User account support
- Ability to create an account
- Save settings across devices, including keyboards

### Keyboard store
- A place where users can post Keyboards to share with each other for free
- Ranking/Review system
- Ability to have a post with what the keyboard offers and details about it
- Trending section

### Image storing
- This will also be a place to store images that are used in the custom keyboards.

This is a pretty short list and i expect it will grow. @Merkie will play a huge role in what these features will be and what they will look like along with the rest of the community.

**Comment by MRSessions** [comment]
1. @fatfingers23 What are the possibilities of adding a .NET Core backend?
2. I have some experience with Azure Storage Blobs, I think that could be a good place for image storage.

**Comment by ariadnimac** [comment]
The keyboard could change according to which words the user uses the most, so that the most used words are at the top and easier to find.

**Comment by IanKnighton** [comment]
1. I'm biased, but I agree with @MRSessions, a .Net Core backend would be a pretty good solution. 
2. Azure AD B2C would be a good option for the Account Creation/Storage. There would need to be some way of linking preferences to a user, but offloading the actual authentication and PII to Azure would alleviate a lot of compliance and security concerns. This could also be done through Auth0 or any other service out there, but I think the Azure approach is nice because you can centralize the management/secrets shared across applications.
